baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'

[params]
numberOfPostsInHomePage = 10 # -n for all posts, 0 for no posts


[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 1

[[menus.main]]
name = 'Posts'
pageRef = '/posts'
weight = 2

[[menus.main]]
name = 'Reading'
pageRef = '/reading'
weight = 3

[[menus.socials]]
name = "Github"
url = "https://github.com"

[[menus.socials]]
name = "X"
url = "https://x.com"

[[menus.footer]]
name = 'Github'
url = "https://github.com"
weight = 1

[[menus.footer]]
name = 'X'
url = "https://x.com"
weight = 2

[[menus.footer]]
name = 'RSS'
url = "/index.xml"
weight = 3


[module]
[module.hugoVersion]
extended = false
min = "0.116.0"
