name = 'Zweifel'
license = 'MIT'
description = "Hugo theme ported from Stefan Zweifel's website"

# The home page of the theme, where the source can be found
homepage = 'https://github.com/wangonya/zweifel.git'

# If you have a running demo of the theme
demosite = 'https://wangonya.com'

# Taxonomy terms
tags = ['blog', 'personal']
features = ['minimal', 'responsive']

# If the theme has multiple authors
authors = [
  { name = 'Stefan Zweifel', homepage = 'https://stefanzweifel.dev' },
  { name = 'Kelvin Wangonya', homepage = 'https://wangonya.com' },
]
